name: Deploy static site to GitHub Pages

on: 
  workflow_dispatch:

  push:
    branches:
      - main
  


permissions:
  pages: write
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Create poem file names manifest
        run: |
          find assets/poems -type f -exec basename {} \; \
            | jq -R . \
            | jq -s . > manifest.json

      - name: Upload static files
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
